Update Schema: Replace ResultDescription with Analytics
smart-data-models/dataModel.SatelliteImagery pull request #8
Opened 2024-12-11 12:56 UTC by DimitrisK19

### What
This PR updates the schema.json, example.json, example.jsonld, example-normalized.json and example-normalized.jsonld files to replace the ResultDescription field with Analytics.

### Why
The update aligns the model to meet the requirements of the "Waterverse" project.

2025-01-29 12:42 UTC, albertoabellagarcia requested changes
everything is ok and it will be approved as long as you do not remove the resultDescription attribute (even if you do not use it)

2025-01-30 15:57 UTC, DimitrisK19 commented
I re-added the resultDescription attribute to all 5 files and pushed the changes, so now it should be ok, thank you!

2025-02-05 10:49 UTC, albertoabellagarcia requested changes
I you change these two comments it would be approved

2025-02-05 12:56 UTC, DimitrisK19 commented
> I you change these two comments it would be approved

Ah I see, I changed those 2 as well! Thank you again!

2025-02-17 09:25 UTC, DimitrisK19 reviewed
Are there any other issues I might have missed?

2025-02-24 17:51 UTC, albertoabellagarcia requested changes
Please address the noted changes.

You can use the new testing process to find out the errors
https://smartdatamodels.org/extra/run_tests.php?repo_url=https://github.com/smart-data-models/dataModel.SatelliteImagery/tree/2dccc0ff04ec5b8a395c446d0e2288f2cc3c3c29/EOSatelliteImagery&email=alberto.abella@fiware.org&only_report_errors=False

and the web form
https://smartdatamodels.org/index.php/test-your-data-model/

2025-02-24 17:51 UTC, albertoabellagarcia commented on EOSatelliteImagery/examples/example-normalized.jsonld
> +  "analytics": {
you have not changed the wrong StructureValue, it has to be replaced by Property

2025-02-25 08:22 UTC, DimitrisK19 reviewed
I made some changes but the testing process still gives some errors/warnings about other attributes etc.

2025-03-06 09:02 UTC, albertoabellagarcia approved these changes
approved

2025-03-06 09:02 UTC, merged